### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by dcmiddle** [target/consensource#6]
The link in README.md to ConsenSource documentation references a github pages location that does not appear to be published:
https://pages.github.com/target/ConsenSource/

**Comment by adeebahmed** [comment]
Yeah, this is an internal resource that needs some refactoring to be public. It is on my backlog to do this!

**Comment by rahealy** [comment]
Speaking of docs:

After deleting my working VM and not remembering what I did to get to issue #2 here are some notes from my attempts at replication that might make sense to put somewhere to save a few hours of research/trial and error.

**Install Ubuntu/Kubuntu Cosmic 18.10 in VM**
Update to latest packages. 
Kubuntu 19.04 Disco Dingo didn't work for me.

**Install Docker and Docker Compose per here:**
https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository
https://docs.docker.com/compose/install/

### Clone and build consensource

Evidently docker by default uses a privileged Unix socket with root permissions. While there's a procedure for creating an additional group and adding users I did not attempt since it wasn't clear that the extra work was preferable to sudo:

`sudo docker-compose -f docker-compose.yaml up`

**Comment by adeebahmed** [comment]
@Patrick-Erichsen is taking this on
